#!/bin/sh

docker run --rm --network="host" -e SONAR_HOST_URL="http://localhost:9000/" -e SONAR_LOGIN="c7b066a68aeb1f0f18ae58b53cb0cd2b31711d44" -v "`pwd`:/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=c7b066a68aeb1f0f18ae58b53cb0cd2b31711d44
